hhwater/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('services/', views.services, name='services'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),
    path('inquiry/', views.inquiry, name='inquiry'),    
 
]

homepage/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class Contact(models.Model):
	Name =     models.CharField(max_length=40,blank=False)
	Email=     models.EmailField(blank=False)
	Phone =    PhoneNumberField()
	Message =  models.TextField(blank=False)
	def __str__(self):
	    return self.Name

class Inquiry(models.Model):
	Ship_Name =                      models.CharField(max_length=40,blank=False)
	Belonging_Country =              models.CharField(max_length=40,blank=False)
	Type_Of_Water =                  models.CharField(max_length=40,blank=False)
	Water_Quantity =                 models.CharField(max_length=40,blank=False)
	Service_required_at_which_port = models.CharField(max_length=40,blank=False)
	Email =                          models.EmailField(blank=False)
	Phone =                          PhoneNumberField()

	def __str__(self):
	    return self.Ship_Name

homepage/forms.py
from django import forms
from phonenumber_field.formfields  import PhoneNumberField
from .fields import ListTextWidget
from .models import Contact, Inquiry

PORTS = (
	'Kandla',
	'Tuna' )

class formContact(forms.ModelForm):
	Name =     forms.CharField(required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
	Email=     forms.EmailField(required=False,widget=forms.TextInput(attrs={'class': 'form-control'}))
	Phone =    PhoneNumberField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'+91 9876543210'}),
                                label='Phone Number(With Country Prifix Code)')
	Message =  forms.CharField(required=True,widget=forms.Textarea(attrs={'class': 'form-control'}))
	class Meta:
	    model = Contact
	    fields = '__all__'

class formInquiry(forms.ModelForm):
	Ship_Name = 			         forms.CharField(required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
	Belonging_Country = 	         forms.CharField(required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
	Type_Of_Water = 		         forms.CharField(required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
	Water_Quantity = 				 forms.CharField(required=True,widget=forms.TextInput(attrs={'class': 'form-control'}))
	Service_required_at_which_port =  forms.CharField(required=True,
                              widget=ListTextWidget(
                                                  data_list=PORTS,
                                                  name='ship-list',
                                                  attrs={'class': 'form-control'}))
	Email=					         forms.EmailField(required=False,widget=forms.TextInput(attrs={'class': 'form-control'}))
	Phone = 				         PhoneNumberField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'+91 9876543210'}), label='Contact Number (Please Provide Country Prifix Code)')
	class Meta:
	    model = Inquiry
	    fields = '__all__'

homepage/views.py
from django.shortcuts import render
from .forms import formContact,formInquiry
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.

def homepage(request):
	return render(request, 'homepage/homepage.html')

def services(request):
	return render(request,'homepage/service.html')

def gallery(request):
	return render(request,'homepage/gallery.html')

def contact(request):
	message = ''
	if request.method == 'POST':
		form = formContact(request.POST)
		if form.is_valid():
			message = 'Thank You For Submitting Contact Form. We Will Reach You Soon. Have A Great Day!'

			Name = form.cleaned_data['Name']
			Email = form.cleaned_data['Email']
			Phone = form.cleaned_data['Phone']
			Message = form.cleaned_data['Message']
			msg = 'Message From Website. \n Name : %s \n Email: %s \n Phone: %s \n Message : %s \n ' %(Name,Email,Phone,Message)
			send_mail(
					'Contact Message From hhwatersupply.com',
					msg,
					settings.EMAIL_HOST_USER,
					['hhwatersupply@gmail.com'],
					fail_silently=True
				)
			form.save()
			form = None

	else:
		form = formContact()

	return render(request, 'homepage/contact.html', {'form':form , 'message':message})

def inquiry(request):
	message = ''
	if request.method == 'POST':
		form = formInquiry(request.POST)
		if form.is_valid():
			message = 'Thank You For Submitting Inquiry Form. We Will Reach You Soon. Have A Great Day!'

			Ship_Name = form.cleaned_data['Ship_Name']
			Belonging_Country = form.cleaned_data['Belonging_Country']
			Type_Of_Water = form.cleaned_data['Type_Of_Water']
			Water_Quantity = form.cleaned_data['Water_Quantity']
			Service_required_at_which_port = form.cleaned_data['Service_required_at_which_port']

			Email = form.cleaned_data['Email']
			Phone = form.cleaned_data['Phone']
			msg = 'Inquiry From Website. \n Ship_Name : %s \n Belonging_Country: %s \n Type_Of_Water: %s \n Water_Quantity: %s \n Service_required_at_which_port: %s \n Email: %s \n Phone: %s \n' %(Ship_Name,Belonging_Country,Type_Of_Water,Water_Quantity,Service_required_at_which_port,Email,Phone)
			send_mail(
					'Inquiry Message From hhwatersupply.com',
					msg,
					settings.EMAIL_HOST_USER,
					['hhwatersupply@gmail.com'],
					fail_silently=True
				)
			form.save()
			form = None

	else:
		form = formInquiry()

	return render(request, 'homepage/inquiry.html', {'form':form , 'message':message})

homepage/templates/homepage/contact.html
{% extends "homepage/navbar.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block content %}
	

<section id="contact">
<style type="text/css">
	.title {
		padding-top: 50px;
		padding-bottom: 50px;
	}
	.title::before {
		content: '';
		background: #7b1789;
		height: 5px;
		width: 300px;
		margin-left: auto;
		margin-right: auto;
		display: block;
		transform: translateY(63px);
	}
	.title::after {
		content: '';
		background: #7b1789;
		height: 10px;
		width: 80px;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 40px;
		display: block;
		transform: translateY(8px);
	}
	form {
		padding-bottom: 50px
	} 
	.form-control{
		    border: 2px solid #ced4da;
		    height: calc(1.5em + .75rem + 10px);
	}
	textarea.form-control {
    	height: 100px;
	}
	.btn-primary {
		box-shadow: none;
		padding: 10px 30px;
		border: 2px solid pink;
		border-radius: 20px;
		background-image: linear-gradient(to right, #a517ba, #5f1782);
	}
	.thanks-div {
		
		background-color: #f3f3f6;
		border-radius: 10px;
		/*padding: 50px*/
		margin-bottom:100px;

	}	
	.thanks {
		font-size: 20px;
		font-weight: 300;
		padding: 30px
	}
</style>


<div class="container text-center">
	<h1 class="title">CONTACT</h1>
{% if form %}	
		<form method="post">
{% csrf_token %}
				<div class="form-row">
					<div class="form-group col-lg-4">

						{{ form.Name|as_crispy_field }}
						
					</div>
					<div class="form-group col-lg-4">

						{{ form.Email|as_crispy_field }}
						
					</div>
					<div class="form-group col-lg-4">

						{{ form.Phone|as_crispy_field }}
						
					</div>
					
				</div>
				<div class="form-row">
					<div class="form-group col-md-12">
						{{ form.Message|as_crispy_field }}
						
					</div>
				</div>
		<input type="submit" value="SUBMIT" class="btn btn-primary">
		</form>
{% else %}
	<div class="text-center thanks-div">
		<p class="thanks">{{message}}</p>
	</div>
{% endif %}
</div>

	
	


</section>

{% endblock %}

homepage/templates/homepage/gallery.html
{% extends "homepage/navbar.html" %}
{% load staticfiles %}
{% block content %}
<style type="text/css">
	.gallery-div {
		padding: 20px;
	}
	.gallery-img {
		padding: 20px;

	}
	.title {
		padding-top: 50px;
		padding-bottom: 50px;
	}
	.title::before {
		content: '';
		background: #7b1789;
		height: 5px;
		width: 300px;
		margin-left: auto;
		margin-right: auto;
		display: block;
		transform: translateY(63px);
	}
	.title::after {
		content: '';
		background: #7b1789;
		height: 10px;
		width: 80px;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 40px;
		display: block;
		transform: translateY(8px);
	}
</style>
<section id="gallery">
	<div class="container text-center">
	<h1 class="title">GALLERY</h1>

		<div class="row gallery-div">
			<div class="col-sm-6 gallery-img">
				<img class="img-fluid" src="{% static 'homepage/img/1.jpg' %}">
			</div>
			<div class="col-sm-6 gallery-img">
				<img class="img-fluid" src="{% static 'homepage/img/2.jpg' %}">
			</div>
		</div>
		<div class="row gallery-div">
			<div class="col-sm-6 gallery-img">
				<img class="img-fluid" src="{% static 'homepage/img/7.jpg' %}">
			</div>
			<div class="col-sm-6 gallery-img">
				<img class="img-fluid" src="{% static 'homepage/img/4.jpg' %}">
			</div>
		</div>
		<div class="row gallery-div">
			<div class="col-sm-6 gallery-img">
				<img class="img-fluid" src="{% static 'homepage/img/5.jpg' %}">
			</div>
			<div class="col-sm-6 gallery-img">
				<img class="img-fluid" src="{% static 'homepage/img/6.jpg' %}">
			</div>
		</div>
		<div class="row gallery-div">
			<div class="col-sm-12 gallery-img">
				<img class="img-fluid" src="{% static 'homepage/img/3.jpg' %}">
			</div>
			
		</div>

	</div>
</section>
{% endblock %}

homepage/templates/homepage/homepage.html
{% extends "homepage/navbar.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
#banner {
		background-image: linear-gradient(to right, #a517ba, #5f1782);
		color: white;
		padding-top: 5%;
	}
	.promo-title {
		font-size: 50px;
		font-weight: 600;
		margin-top: 100px;
		font-family: 'Halant', serif;
	}
	.bottom-img {
		width:  100%;
	}
	.promo-subtitle {
		font-size: 1.2rem;
	}
	.btn-primary {
		box-shadow: none;
		padding: 10px 30px;
		border: 2px solid #7b1789;
		border-radius: 30px;
		background-image: linear-gradient(to right, #5f1782,#a517ba);
	}

</style>
<link href="https://fonts.googleapis.com/css?family=Halant&display=swap" rel="stylesheet">

<section id="banner">
	<div class="container">
		<div class="row">
			<div class="col-md-6 text-center">
				<p class="promo-title text-center">H H WATER SUPPLY</p>
				<p class="promo-subtitle text-center">Fresh Water Supply & Ship Chandling</p>
				<a href="tel:+91 9824286952"><button class="btn btn-primary"><i class="fa fa-phone"></i> Click To Call</button></a>
			</div>
			<div class="col-md-6 text-center">
				<img class="img-fluid" src="{% static 'homepage/img/main_image.png' %}">
			</div>
		</div>
	</div>
	<img class="bottom-img" src="{% static 'homepage/img/bottom-img_1.png' %}">
</section>


<style type="text/css">
	.title::before {
		content: '';
		background: #7b1789;
		height: 5px;
		width: 300px;
		margin-left: auto;
		margin-right: auto;
		display: block;
		transform: translateY(63px);
	}
	.title::after {
		content: '';
		background: #7b1789;
		height: 10px;
		width: 80px;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 40px;
		display: block;
		transform: translateY(8px);
	}

	#about-us {
		padding-bottom: 50px;
		padding-top: 50px;
	}
	.about-title {
		font-size: 30px;
		font-weight: 600;
		margin-top: 8%;
	}
	#about-us ul li {
		margin: 10px 0;
	}
	#about-us ul{
		margin-left: 20px;
	}

</style>
{% url 'homepage:inquiry' as inquiry %}
<section id="about-us">
	<div class="container">
		<h1 class="title text-center">ABOUT US</h1>
		<div class="row">
			<div class="col-md-6">
				<img class="img-fluid" src="{% static 'homepage/img/about.png' %}">
			</div>
			<div class="col-md-6">
				<p class="about-title">Why We Are Different?</p>
			    <p> H H Water Supply has rich experience of 10+ years in supplying Fresh Water and in Ship Chandling facility.
                    We manage significant values on behalf of our customers.
                    We take responsibility for the job being done in a professional, cost-effective manner that preserves their assets and reputation.
			    </p>
			    <a href="{{ inquiry }}"><button class="btn btn-primary">GET A QUOTE</button></a>
			</div>

		</div>
	</div>
</section>
{% endblock %}

homepage/templates/homepage/inquiry.html
{% extends "homepage/navbar.html" %}
{% load staticfiles %}
{% block content %}

<section id="inquiry">
<style type="text/css">
	.title {
		padding-top: 50px;
		padding-bottom: 50px;
	}
	.title::before {
		content: '';
		background: #7b1789;
		height: 5px;
		width: 300px;
		margin-left: auto;
		margin-right: auto;
		display: block;
		transform: translateY(63px);
	}
	.title::after {
		content: '';
		background: #7b1789;
		height: 10px;
		width: 80px;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 40px;
		display: block;
		transform: translateY(8px);
	}
	form {
		padding-bottom: 50px
	} 
	.form-control{
		    border: 2px solid #ced4da;
		    height: calc(1.5em + .75rem + 10px);
	}
	textarea.form-control {
    	height: 100px;
	}
	.btn-primary {
		box-shadow: none;
		padding: 10px 30px;
		border: 2px solid pink;
		border-radius: 20px;
		background-image: linear-gradient(to right, #a517ba, #5f1782);
	}
	.thanks-div {
		
		background-color: #f3f3f6;
		border-radius: 10px;
		/*padding: 50px*/
		margin-bottom:100px;

	}	
	.thanks {
		font-size: 20px;
		font-weight: 300;
		padding: 30px
	}
</style>


<div class="container">
	<h1 class="title text-center">INQUIRY</h1>
{% if form %}	
		<form method="post">
{% csrf_token %}
		<div class="row">
			<div class="col-md-8 offset-md-2">
				{{ form.as_p }}
			</div>
		</div>
		
		<div class="text-center">
			<input align="center" type="submit" value="SUBMIT" class="btn btn-primary">
		</div>	
		
		</form>
{% else %}
	<div class="text-center thanks-div">
		<p class="thanks">{{message}}</p>
	</div>
{% endif %}
</div>

	
	


</section>


{% endblock %}

homepage/templates/homepage/navbar.html
{% load staticfiles %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
<head>
	<title>H H WATER SUPPLY</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="https://fonts.googleapis.com/css?family=Halant&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css">
	

</head>
<body>
<style type="text/css">
	* {
			margin: 0;
			padding: 0;
		}
		body {
			overflow-x: hidden;
		}
		#nav-bar {
			position: sticky;
			top: 0;
			z-index: 10;
		}
		.navbar {
			background-image: linear-gradient(to right, #a517ba, #5f1782);
			padding: 0 !important;
		}
		.navbar-nav li{
			padding: 0 10px;
		}
		.navbar-nav li a{
			color: #fff !important;
			font-weight: 600;
			float: right;
			text-align: left;
		}
		.navbar-toggler-icon {

		}
		.navbar-brand h4{
			color: white;
			padding-left: 10px;
			font-family: 'Halant', serif;
			margin-bottom: 0;
			padding: 10px

		}
		.fa-bars {
			color: #fff;
			font-size: 30px !important;
		}
		.navbar-toggler {
			outline: none !important;
		}
		section {
			border: none;
		}#wpforo-wrap .wpforo-forum-icon {
    display: block !important;
}

@media screen and (max-width: 620px)
    #wpforo-wrap .wpfl-1 .wpforo-forum-info {
    width: auto !important;
}
</style>
<section id="nav-bar">
	 	{% url 'homepage:homepage' as homepage %}
        {% url 'homepage:services' as services %}
        {% url 'homepage:gallery' as gallery %}
        {% url 'homepage:contact' as contact %}
        {% url 'homepage:inquiry' as inquiry %}
	<nav class="navbar navbar-expand-lg navbar-dark bg-light">
	  <a class="navbar-brand" href="#"><h4 >H H WATER SUPPLY</h4></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarNav">
	    <ul class="navbar-nav ml-auto">
	      <li {% if request.path == homepage %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
	        <a class="nav-link" href="{{ homepage }}">HOME</a>
	      </li>
	      <li {% if request.path == services %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
	        <a class="nav-link" href="{{ services }}">SERVICES</a>
	      </li>
	      <li {% if request.path == gallery %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
	        <a class="nav-link" href="{{ gallery }}">GALLERY</a>
	      </li>
	      <li {% if request.path == inquiry %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
	        <a class="nav-link" href="{{ inquiry }}">INQUIRY</a>
	      </li>
	      <li {% if request.path == contact %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
	        <a class="nav-link" href="{{ contact }}">CONTACT</a>
	      </li>
	    </ul>
	  </div>
	</nav>
</section>

{% block content %}





















{% endblock %}

<style type="text/css">
	#footer {
		background-image: linear-gradient(to right, #a517ba, #5f1782);
		color: #fff;
	}
	.footer-img {
		width: 100%;
	}
	.footer-box {
		padding: 20px;
	}
	.footer-box img {
		width: 120px;
		margin-bottom: 20px;
	}
	.footer-box .fas {
		margin-right: 8px;
		font-size: 25px;
		height: 40px;
		width: 40px;
		text-align: center;
		padding-top: 7px;
		border-radius: 2px;
		background-image: linear-gradient(to right, #a517ba, #5f1782);
	}
	.footer-box .far {
		margin-right: 8px;
		font-size: 25px;
		height: 40px;
		width: 40px;
		text-align: center;
		padding-top: 7px;
		border-radius: 2px;
		background-image: linear-gradient(to right, #a517ba, #5f1782);
	}
	hr {
		background-color: white;
	}
	.copywrite {
		margin-bottom: 0;
		padding-bottom: 20px;
		text-align: center;
	}

</style>


<section id="footer">
	<img class="footer-img" src="{% static 'homepage/img/bottom-img_12.png' %}">
	<div class="container">
		<h3></h3>
		<div class="row">
		
			<div class="col-md-6 footer-box">
				<img src="">	
				<p><i class="fas fa-map-marker-alt"></i> <b>ADDRESS</b></p>
				<div style="padding-left: 55px">
				<p> 2, Lalji Chamber,<br> 
					National Highway No. 8/A, <br>
					Opp. FCI Godown, KASEZ, <br>
					Gandhidham - 370 201,<br>
					Gujarat(INDIA)</p>
	
				</div>
				
				<p><i class="fas fa-phone-volume"></i></i> (+91) 9824286952 / 8141380555</p>
				<p><i class="far fa-envelope"></i></i>hhwatersupply@gmail.com<gmail class="com"></gmail></p>
				<p></p>
			</div>
			
			<div class="col-md-6 text-center">
					<img class="footer-img" src="{% static 'homepage/img/12.png' %}">
				
			</div>
			</div>

			<hr>
			<p class="copywrite">copywrite © 2019 H H WATER SUPPLY</p>
			<p class="copywrite">Designed By: ShreejiDevelopers</p>
		</div>
		
	
</section>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

homepage/templates/homepage/service.html
{% extends "homepage/navbar.html" %}
{% load staticfiles %}
{% block content %}

<style type="text/css">
	#services {
		padding: 80px 0;
	}
	.service_img {
		width: 30%;
		margin-top: 20px
	}
	.services {
		padding: 20px;
		/*border: 1px solid black;*/
	}
	.services h4 {
		padding: 5px;
		margin-top: 25px;
		text-transform: uppercase;
	}
	.title {
		padding-top: 20px;
		padding-bottom: 50px;
	}
	.title::before {
		content: '';
		background: #7b1789;
		height: 5px;
		width: 300px;
		margin-left: auto;
		margin-right: auto;
		display: block;
		transform: translateY(63px);
	}
	.title::after {
		content: '';
		background: #7b1789;
		height: 10px;
		width: 80px;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 40px;
		display: block;
		transform: translateY(8px);
	}
	.xyz{
	    padding: 45px 25px;
	    background: #f3f3f6;
		border: 20px solid white;
		border-radius: 30px
	}


</style>

<section id="services">
	<div class="container text-center">
		<h1 class="title">SERVICES</h1>
		<div class="row text-center">
			<div class="col-sm-6 services xyz">
				<img class="img-fluid service_img" src="{% static 'homepage/img/ro.png' %}">
				<h4>RO Water</h4>
				<p style="text-align: justify;">Reverse osmosis is a process where broken down or dissolved unnatural materials are extracted from water using a semipermeable membrane. It ensures drinking water is pure.</p>
			</div>
			<div class="col-sm-6 services xyz">
				<img class="img-fluid service_img" src="{% static 'homepage/img/dm.png' %}">

				<h4>DM Water</h4>
				<p style="text-align: justify;">Demineralised water is specially purified water that has had most or all of its mineral and salt ions removed, such as Calcium, Magnesium, Sodium, Chloride, Sulphate, Nitrate and Bicarbonate. It is also known as Deionised water, DI or Demin water.</p>
			</div>
		</div>
		<div class="row text-center">
			<div class="col-sm-6 services xyz">
				<img class="img-fluid service_img" src="{% static 'homepage/img/iodise.png' %}">

				<h4>Iodine Wash Salt</h4>
				<p style="text-align: justify;"> After harvest, the salt is washed, drained, cleaned and refined. This is the purest way to harvest salt, often resulting in nearly 100 percent sodium chloride.</p>
			</div>
			<div class="col-sm-6 services xyz">
				<img class="img-fluid service_img" src="{% static 'homepage/img/borewell.png' %}">

				<h4>Borwell Water</h4>
				<p style="text-align: justify;">
				    Bore water is groundwater that has been accessed by drilling a bore into underground aquifers (water storages) and pumping to the surface.
				</p>
			</div>
		</div>
	</div>
</section>

{% endblock %}